import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavbarBottom from "../components/NavbarBottom";
import { UserProvider } from "@/context/UserContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider>
          {children}
          <NavbarBottom></NavbarBottom>
          <Toaster
            position="top-center"
            toastOptions={{
              success: {
                iconTheme: {
                  primary: "whitesmoke",
                  secondary: "black",
                },
                style: {
                  background: "#4f8f42",
                  color: "whitesmoke",
                  fontSize: "1.3rem",
                },
              },
              error: {
                iconTheme: {
                  primary: "whitesmoke",
                  secondary: "red",
                },
                style: {
                  background: "tomato",
                  color: "whitesmoke",
                  fontSize: "1.3rem",
                  minWidth:"520px",
                  wordWrap: "break-word",
                  wordBreak:"break-all"
                },
              },
            }}
          />
        </UserProvider>
      </body>
    </html>
  );
}
