import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavbarBottom from "../components/NavbarBottom";
import { UserProvider } from "@/context/UserContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "VoIP Device Config",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider>
          {children}
          <NavbarBottom></NavbarBottom>
          <Toaster
            position="top-center"
            toastOptions={{
              success: {
                iconTheme: {
                  primary: "whitesmoke",
                  secondary: "black",
                },
                style: {
                  background: "#44A08D",

                  background: "linear-gradient(to bottom, #093637, #44A08D)",

                  color: "whitesmoke",
                  fontSize: "1rem",
                },
              },
              error: {
                iconTheme: {
                  primary: "whitesmoke",
                  secondary: "red",
                },
                style: {
                  background: "#ff0084",

                  background: "linear-gradient(to bottom, #33001b, #ff0084)",

                  color: "whitesmoke",
                  fontSize: "1rem",
                },
              },
            }}
          />
        </UserProvider>
      </body>
    </html>
  );
}
