import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import SessionToast from "../components/SessionToast";
import NavbarBottom from "../components/NavbarBottom";
import { UserProvider } from "@/context/UserContext";
import { ThemeProvider } from "@/context/ThemeContext";
import { Toaster } from "react-hot-toast";
import ThemeToggle from "@/components/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "VoIP Device Config",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider>
          <ThemeProvider>
            <ThemeToggle></ThemeToggle>
            {children}
            <SessionToast></SessionToast>
            <NavbarBottom></NavbarBottom>
            <Toaster
              position="top-center"
              toastOptions={{
                success: {
                  iconTheme: {
                    primary: "whitesmoke",
                    secondary: "black",
                  },
                  style: {
                    background: "#44A08D",

                    background: "linear-gradient(to bottom, #093637, #44A08D)",

                    color: "whitesmoke",
                    fontSize: "1rem",
                  },
                },
                error: {
                  iconTheme: {
                    primary: "whitesmoke",
                    secondary: "red",
                  },
                  style: {
                    background: "#ff0084",

                    background: "linear-gradient(to bottom, #33001b, #ff0084)",

                    color: "whitesmoke",
                    fontSize: "1rem",
                  },
                },
              }}
            />
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}
