export const phones = [
  {
    name: "Grandstream GXP_1625 (SIP telefon)",
    type: "Grandstream",
    model: "GXP_1625",
    port: 1,
    image: "/images/GXP1625.png",
  },
  {
    name: "Grandstream HT814 (4-portni RGW)",
    type: "Grandstream",
    model: "HT814",
    port: 4,
    image: "/images/HT814.png",
  },
  {
    name: "Grandstream HT818 (8-portni RGW)",
    type: "Grandstream",
    model: "HT818",
    port: 8,
    image: "/images/HT818.png",
  },
  {
    name: "Grandstream GXW4216 (16-portni RGW)",
    type: "Grandstream",
    model: "GXW4216",
    port: 16,
    image: "/images/GXW4216.jpg",
  },
  {
    name: "Grandstream GXW4224 (24-portni RGW)",
    type: "Grandstream",
    model: "GXW4224",
    port: 24,
    image: "/images/GXW4224.png",
  },
  {
    name: "Polycom IP331 (SIP telefon)",
    type: "Polycom",
    model: "IP331",
    port: 1,
    image: "/images/IP331.png",
  },
  {
    name: "Polycom IP650 (SIP telefon)",
    type: "Polycom",
    model: "IP650",
    port: 1,
    image: "/images/IP650.jpg",
  },
  {
    name: "Polycom VVX350 (SIP telefon)",
    type: "Polycom",
    model: "VVX350",
    port: 1,
    image: "/images/VVX350.png",
  },
  {
    name: "Cisco 502G (SIP telefon)",
    type: "Cisco",
    model: "502G",
    port: 1,
    image: "/images/SPA502G.png",
  },
  {
    name: "Cisco 512G (SIP telefon)",
    type: "Cisco",
    model: "512G",
    port: 1,
    image: "/images/SPA512G.png",
  },
  {
    name: "Fanvil V62GG (SIP telefon)",
    type: "Fanvil",
    model: "V62G",
    port: 1,
    image: "/images/V62G.png",
  },
  {
    name: "Fanvil X3U (SIP telefon)",
    type: "Fanvil",
    model: "X3U",
    port: 1,
    image: "/images/X3U.png",
  },
  {
    name: "Fanvil X7C (SIP telefon)",
    type: "Fanvil",
    model: "X7C",
    port: 1,
    image: "/images/X7C.png",
  },
  {
    name: "Yealink DECT (SIP telefon)",
    type: "Yealink",
    model: "DECT",
    port: 1,
    image: "/images/DECT.webp",
  },
  {
    name: "Yealink T31G (SIP telefon)",
    type: "Yealink",
    model: "T31G",
    port: 1,
    image: "/images/SIP-T31G.png",
  },
  {
    name: "Yealink T430U (SIP telefon)",
    type: "Yealink",
    model: "T430U",
    port: 1,
    image: "/images/SIP-T430U.jpg",
  },
  {
    name: "Panasonic KX-TGP600 DECT (SIP telefon)",
    type: "Panasonic",
    model: "KX-TGP600",
    port: 1,
    image: "/images/KX-TGP600.png",
  },
];

export const phoneTypes = Array.from(
  new Set(phones.map((phone) => phone.type))
);
