export const phones = [
  {
    name: "SIP telefon (Grandstream GXP_1625)",
    type: "Grandstream",
    model: "GXP_1625",
    port: 1,
    image: "/images/GXP1625.png",
  },
  {
    name: "4-portni RGW (Grandstream HT814)",
    type: "Grandstream",
    model: "HT814",
    port: 4,
    image: "/images/HT814.png",
  },
  {
    name: "8-portni RGW (Grandstream HT818)",
    type: "Grandstream",
    model: "HT818",
    port: 8,
    image: "/images/HT818.png",
  },
  {
    name: "16-portni RGW (Grandstream GXW4216)",
    type: "Grandstream",
    model: "GXW4216",
    port: 16,
    image: "/images/GXW4216.png",
  },
  {
    name: "24-portni RGW (Grandstream GXW4224)",
    type: "Grandstream",
    model: "GXW4224",
    port: 24,
    image: "/images/GXW4224.png",
  },
  {
    name: "SIP telefon (Polycom IP331)",
    type: "Polycom",
    model: "IP331",
    port: 1,
    image: "/images/IP331.png",
  },
  {
    name: "SIP telefon (Polycom IP650)",
    type: "Polycom",
    model: "IP650",
    port: 1,
    image: "/images/X30.png",
  },
  {
    name: "SIP telefon (Cisco 502G)",
    type: "Cisco",
    model: "502G",
    port: 1,
    image: "/images/SPA502G.png",
  },
  {
    name: "SIP telefon (Cisco 512G)",
    type: "Cisco",
    model: "512G",
    port: 1,
    image: "/images/SPA512G.png",
  },
];
