export const phones = [
  {
    name: "Grandstream GXP_1625 (SIP telefon)",
    type: "Grandstream",
    model: "GXP_1625",
    port: 1,
    image: "/images/GXP1625.png",
  },
  {
    name: "Grandstream HT814 (4-portni RGW)",
    type: "Grandstream",
    model: "HT814",
    port: 4,
    image: "/images/HT814.png",
  },
  {
    name: "Grandstream HT818 (8-portni RGW)",
    type: "Grandstream",
    model: "HT818",
    port: 8,
    image: "/images/HT818.png",
  },
  {
    name: "Grandstream GXW4216 (16-portni RGW)",
    type: "Grandstream",
    model: "GXW4216",
    port: 16,
    image: "/images/GXW4216.jpg",
  },
  {
    name: "Grandstream GXW4224 (24-portni RGW)",
    type: "Grandstream",
    model: "GXW4224",
    port: 24,
    image: "/images/GXW4224.png",
  },
  {
    name: "Polycom IP331 (SIP telefon)",
    type: "Polycom",
    model: "IP331",
    port: 1,
    image: "/images/IP331.png",
  },
  {
    name: "Polycom IP650 (SIP telefon)",
    type: "Polycom",
    model: "IP650",
    port: 1,
    image: "/images/IP650.jpg",
  },
  {
    name: "Cisco 502G (SIP telefon)",
    type: "Cisco",
    model: "502G",
    port: 1,
    image: "/images/SPA502G.png",
  },
  {
    name: "Cisco 512G (SIP telefon)",
    type: "Cisco",
    model: "512G",
    port: 1,
    image: "/images/SPA512G.png",
  },
];
