export const phoneConfig = [
  {
    model: "GXP_1625",
    path: "xmlconfigs/Grandstream",
    encrypt: true,
    prefix: "cfg",
    extension: ".xml",
  },
  {
    model: "HT814",
    path: "xmlconfigs/Grandstream",
    encrypt: true,
    prefix: "cfg",
    extension: ".xml",
  },
  {
    model: "HT818",
    path: "xmlconfigs/Grandstream",
    encrypt: true,
    prefix: "cfg",
    extension: ".xml",
  },
  {
    model: "GXW4216",
    path: "xmlconfigs/Grandstream",
    encrypt: true,
    prefix: "cfg",
    extension: ".xml",
  },
  {
    model: "GXW4224",
    path: "xmlconfigs/Grandstream",
    encrypt: true,
    prefix: "cfg",
    extension: ".xml",
  },
  {
    model: "IP331",
    path: "xmlconfigs",
    encrypt: false,
    prefix: "phone1",
    extension: ".cfg",
  },
  {
    model: "IP650",
    path: "xmlconfigs",
    encrypt: false,
    prefix: "phone1",
    extension: ".cfg",
  },
  {
    model: "502G",
    path: "xmlconfigs/Cisco502G",
    encrypt: false,
    prefix: "spa502g_",
    extension: ".xml",
  },
  {
    model: "512G",
    path: "xmlconfigs/Cisco512G",
    encrypt: false,
    prefix: "spa512g_",
    extension: ".xml",
  },
];
